// <auto-generated />
using System;
using EntityFrameworkCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.Data.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore.Domain.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasFilter("[TeamId] IS NOT NULL");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(690),
                            Name = "Coach 1",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(690),
                            Name = "Coach 2",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(690),
                            Name = "Coach 3",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(690),
                            Name = "Coach 4",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(690),
                            Name = "Coach 5",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(690),
                            Name = "Coach 6",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(690),
                            Name = "Coach 7",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(690),
                            Name = "Coach 8",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(700),
                            Name = "Coach 9",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(700),
                            Name = "Coach 10",
                            TeamId = 10
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(580),
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(580),
                            Name = "Premier League"
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(720),
                            Date = new DateTime(2024, 6, 5, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(720),
                            HomeTeamId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(720),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            Date = new DateTime(2024, 6, 6, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            HomeTeamId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            Date = new DateTime(2024, 6, 7, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            HomeTeamId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 4,
                            AwayTeamId = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            Date = new DateTime(2024, 6, 8, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            HomeTeamId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 5,
                            AwayTeamId = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            Date = new DateTime(2024, 6, 9, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            HomeTeamId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 6,
                            AwayTeamId = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            Date = new DateTime(2024, 6, 10, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            HomeTeamId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 7,
                            AwayTeamId = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            Date = new DateTime(2024, 6, 11, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            HomeTeamId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(730),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 8,
                            AwayTeamId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 12, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 9,
                            AwayTeamId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 13, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 10,
                            AwayTeamId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 14, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 2,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 11,
                            AwayTeamId = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 15, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 2,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 12,
                            AwayTeamId = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 16, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 2,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 13,
                            AwayTeamId = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 17, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 2,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 14,
                            AwayTeamId = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 18, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 2,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 15,
                            AwayTeamId = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 19, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 2,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 16,
                            AwayTeamId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 20, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 2,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 17,
                            AwayTeamId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 21, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 2,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 18,
                            AwayTeamId = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            Date = new DateTime(2024, 6, 22, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 3,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 19,
                            AwayTeamId = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 6, 23, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(740),
                            HomeTeamId = 3,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 20,
                            AwayTeamId = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 6, 24, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 3,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 21,
                            AwayTeamId = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 6, 25, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 3,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 22,
                            AwayTeamId = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 6, 26, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 3,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 23,
                            AwayTeamId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 6, 27, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 3,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 24,
                            AwayTeamId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 6, 28, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 3,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 25,
                            AwayTeamId = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 6, 29, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 4,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 26,
                            AwayTeamId = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 6, 30, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 4,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 27,
                            AwayTeamId = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 7, 1, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 4,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 28,
                            AwayTeamId = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 7, 2, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 4,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 29,
                            AwayTeamId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 7, 3, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 4,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 30,
                            AwayTeamId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            Date = new DateTime(2024, 7, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            HomeTeamId = 4,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(750),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 31,
                            AwayTeamId = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 5, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 5,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 32,
                            AwayTeamId = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 6, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 5,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 33,
                            AwayTeamId = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 7, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 5,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 34,
                            AwayTeamId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 8, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 5,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 35,
                            AwayTeamId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 9, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 5,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 36,
                            AwayTeamId = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 10, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 6,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 37,
                            AwayTeamId = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 11, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 6,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 38,
                            AwayTeamId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 12, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 6,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 39,
                            AwayTeamId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 13, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 6,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 40,
                            AwayTeamId = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 14, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 7,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 41,
                            AwayTeamId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 15, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 7,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 42,
                            AwayTeamId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            Date = new DateTime(2024, 7, 16, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(760),
                            HomeTeamId = 7,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 43,
                            AwayTeamId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            Date = new DateTime(2024, 7, 17, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            HomeTeamId = 8,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 44,
                            AwayTeamId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            Date = new DateTime(2024, 7, 18, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            HomeTeamId = 8,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 45,
                            AwayTeamId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            Date = new DateTime(2024, 7, 19, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            HomeTeamId = 9,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(770),
                            TicketPrice = 50m
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(650),
                            Name = "Team 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(650),
                            Name = "Team 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(660),
                            Name = "Team 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(660),
                            Name = "Team 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(660),
                            Name = "Team 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(660),
                            Name = "Team 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(660),
                            Name = "Team 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(660),
                            Name = "Team 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(660),
                            Name = "Team 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            ModifiedBy = "System",
                            ModifiedDate = new DateTime(2024, 6, 4, 22, 37, 31, 656, DateTimeKind.Utc).AddTicks(660),
                            Name = "Team 10"
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.Coach", b =>
                {
                    b.HasOne("EntityFrameworkCore.Domain.Team", "Team")
                        .WithOne("Coach")
                        .HasForeignKey("EntityFrameworkCore.Domain.Coach", "TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.Match", b =>
                {
                    b.HasOne("EntityFrameworkCore.Domain.Team", "AwayTeam")
                        .WithMany("MatchAwayTeams")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityFrameworkCore.Domain.Team", "HomeTeam")
                        .WithMany("MatchHomeTeams")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.Team", b =>
                {
                    b.HasOne("EntityFrameworkCore.Domain.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.Team", b =>
                {
                    b.Navigation("Coach");

                    b.Navigation("MatchAwayTeams");

                    b.Navigation("MatchHomeTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
